### ISSUE TITLE
catkin_pkg does not support more than 3 part in version string.

### ISSUE THREAD

**Issue by asmodehn** [ros-infrastructure/catkin_pkg#149]
I am trying to release [python-certifi](https://github.com/certifi/python-certifi) as a thirdparty package.

As you can see, the version schema they have chosen follows : yyyy.mm.dd.patch.

Note the patch part is present in their stable stream, which makes it even more important when doing thirdparty releases for ROS, where the point is to rely on stable version of system dependencies (instead of latest pip version)

However catkin_pkg does not support more than 3 numbers in the version string : 
```
Traceback (most recent call last):
  File "/usr/bin/git-bloom-import-upstream", line 9, in <module>
    load_entry_point('bloom==0.5.21', 'console_scripts', 'git-bloom-import-upstream')()
  File "/usr/lib/python2.7/dist-packages/bloom/commands/git/import_upstream.py", line 391, in main
    args.replace)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/git/import_upstream.py", line 324, in import_upstream
    _, actual_version, _ = get_package_data('upstream')
  File "/usr/lib/python2.7/dist-packages/bloom/packages.py", line 83, in get_package_data
    packages = find_packages(repo_dir)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 83, in find_packages
    packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 110, in find_packages_allowing_duplicates
    packages[path] = parse_package(os.path.join(basepath, path), warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 370, in parse_package
    return parse_package_string(f.read(), filename, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 543, in parse_package_string
    pkg.validate(warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 244, in validate
    raise InvalidPackage('\n'.join(errors))
InvalidPackage: Invalid package manifest "/tmp/tmpruF0Hh/./package.xml": Package version "2015.11.20.1" does not follow version conventions
```

Is this something we can consider fixing, without breaking the useful version check for ROS packages ?

**Comment by wjwwood** [comment]
I do not believe it makes sense to update all of our infrastructure to support more than `x.y.z`. You'd also have to fix bloom, the build farm, and possibly other parts of the system.

**Comment by tfoote** [comment]
The x.y.z version is as per [REP 140](http://www.ros.org/reps/rep-0140.html#version) and matches [semantic versioning](http://semver.org/)

**Comment by asmodehn** [comment]
I managed to specify the version and the release tag it just like [that](https://github.com/asmodehn/certifi-rosrelease/blob/master/tracks.yaml), so thats fine, as I wont release update very often.
Cheers !
