### ISSUE TITLE
TypeError during `catkin_generate_changelog`

### ISSUE THREAD

**Issue by allenh1** [ros-infrastructure/catkin_pkg#172]
*note:* this is likely just a Gentoo problem. So forgive me when that's the case. ;)

Upon trying to release `p2os`, I received the following:

```
allenh1@localhost ~/catkin_ws/src/p2os $ catkin_generate_changelog 
Found packages: p2os_doc, p2os_driver, p2os_launch, p2os_msgs, p2os_teleop, p2os_urdf
Querying commit information since latest tag...
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.5/catkin_generate_changelog", line 11, in <module>
    load_entry_point('catkin-pkg==0.3.1', 'console_scripts', 'catkin_generate_changelog')()
  File "/usr/lib64/python3.5/site-packages/catkin_pkg/cli/generate_changelog.py", line 120, in main_catching_runtime_error
    main(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/catkin_pkg/cli/generate_changelog.py", line 104, in main
    tag2log_entries = get_forthcoming_changes(vcs_client, skip_merges=args.skip_merges)
  File "/usr/lib64/python3.5/site-packages/catkin_pkg/changelog_generator.py", line 69, in get_forthcoming_changes
    tags = _get_version_tags(vcs_client)
  File "/usr/lib64/python3.5/site-packages/catkin_pkg/changelog_generator.py", line 89, in _get_version_tags
    tags = vcs_client.get_tags()
  File "/usr/lib64/python3.5/site-packages/catkin_pkg/changelog_generator_vcs.py", line 155, in get_tags
    decorations = ', '.join(re.findall('^[a-f0-9]+ \(([^)]*)\) .', result_tag['output'], re.MULTILINE)) + ','
  File "/usr/lib64/python3.5/re.py", line 213, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object
```

I'm using Python 3.5, catkin_pkg 0.3.1, bloom 0.5.26, and ros lunar.

My thoughts are that this is likely some strange ascii/utf-8 encoding problem. Maybe there needs to be a `.decode('utf-8')` somewhere?

**Comment by dirk-thomas** [comment]
This is actually a Python 3 specific problem which happens the same on other platforms. Please see #173 for a proposed fix. It would be great if you could give it a try and comment if it fixes the problem for you.
