### ISSUE TITLE
catkin_pkg >= 0.3.2 spawns a lot of roslaunch process

### ISSUE THREAD

**Issue by k-okada** [ros-infrastructure/catkin_pkg#175]
I'm not sure if this is related to https://github.com/ros-infrastructure/catkin_pkg/pull/174, after we update `catkin_pkg` >= 0.3.2 and still in 0.3.3, we have problem on `roslaunch` a program within catkin work space

- `source devel/setup.bash` and `roslaunch roscpp_tutorials talker_listener.launch` do not start programs, and spawn may (+100) roslaunch process, C-c takes log time.
- `source /opt/ros/indigo/setup.bash` and `roslaunch roscpp_tutorials talker_listener.launch` is ok
- `CMAKE_PREFIX_PATH=/opt/ros/indigo roslaunch /tmp/catkin_ws/src/ros_tutorials/roscpp_tutorials/launch/talker_listener.launch` is also ok

if we downgrade catkin_pkg to 0.3.1, issues has gone.

Cc: @YutoUchimi

```
uchimi@sheeta:/tmp/catkin_ws$ roslaunch roscpp_tutorials talker_listener.launch ... logging to /home/uchimi/.ros/log/020611cc-40ff-11e7-aa25-8cdcd4282014/roslaunch-sheeta-15853.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://sheeta:40770/

SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    listener (roscpp_tutorials/listener)
    talker (roscpp_tutorials/talker)

auto-starting new master
process[master]: started with pid [16069]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 020611cc-40ff-11e7-aa25-8cdcd4282014
^CProcess PoolWorker-161:
Process PoolWorker-187:
Process PoolWorker-192:
Traceback (most recent call last):
Process PoolWorker-189:
Process PoolWorker-160:
Process PoolWorker-188:
Process PoolWorker-186:
Process PoolWorker-146:
Process PoolWorker-134:
Traceback (most recent call last):
Process PoolWorker-135:
Traceback (most recent call last):
Process PoolWorker-113:
Traceback (most recent call last):
Process PoolWorker-123:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
Process PoolWorker-110:
Traceback (most recent call last):
Process PoolWorker-107:
Process PoolWorker-106:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-147:
Traceback (most recent call last):
Process PoolWorker-69:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-93:
Traceback (most recent call last):
Process PoolWorker-78:
Process PoolWorker-75:
Process PoolWorker-64:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-63:
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Process PoolWorker-27:
Traceback (most recent call last):
    self.run()
    self.run()
    self.run()
Process PoolWorker-29:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-18:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Process PoolWorker-21:
Process PoolWorker-33:
Traceback (most recent call last):
Process PoolWorker-22:
Process PoolWorker-24:
Process PoolWorker-30:
Process PoolWorker-7:
Traceback (most recent call last):
Process PoolWorker-36:
Traceback (most recent call last):
Process PoolWorker-35:
Process PoolWorker-71:
Process PoolWorker-34:
Traceback (most recent call last):
Process PoolWorker-108:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
Process PoolWorker-32:
Process PoolWorker-70:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-105:
Process PoolWorker-145:
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
Process PoolWorker-31:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Process PoolWorker-68:
Process PoolWorker-144:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-28:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-104:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Process PoolWorker-180:
    self.run()
Process PoolWorker-67:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-26:
Traceback (most recent call last):
Process PoolWorker-143:
Process PoolWorker-103:
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-66:
Process PoolWorker-179:
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 374, in get
Process PoolWorker-25:
Traceback (most recent call last):
Process PoolWorker-142:
Traceback (most recent call last):
Process PoolWorker-102:

.....

KeyboardInterrupt
KeyboardInterrupt
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
KeyboardInterrupt
    racquire()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 374, in get
KeyboardInterrupt
KeyboardInterrupt
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    racquire()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 374, in get
    racquire()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
    racquire()
    task = get()
KeyboardInterrupt
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 374, in get
    racquire()
KeyboardInterrupt
cannot add process [rosout-1] after process monitor has been shut down
The traceback for the exception was written to the log file
^Z
[1]+  Stopped                 roslaunch roscpp_tutorials talker_listener.launch
uchimi@sheeta:/tmp/catkin_ws$ kill %1
uchimi@sheeta:/tmp/catkin_ws$ CMAKE_PREFIX_PATH=/opt/ros/indigo roslaunch roscpp_tutorials talker_listener.launch 
multiple files named [talker_listener.launch] in package [roscpp_tutorials]:
- /opt/ros/indigo/share/roscpp_tutorials/launch/talker_listener.launch
- /tmp/catkin_ws/src/ros_tutorials/roscpp_tutorials/launch/talker_listener.launch
Please specify full path instead
The traceback for the exception was written to the log file
uchimi@sheeta:/tmp/catkin_ws$ CMAKE_PREFIX_PATH=/opt/ros/indigo roslaunch /tmp/catkin_ws/src/ros_tutorials/roscpp_tutorials/launch/talker_listener.launch
... logging to /home/uchimi/.ros/log/29f44e7e-40ff-11e7-848f-8cdcd4282014/roslaunch-sheeta-17032.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://sheeta:46699/

SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    listener (roscpp_tutorials/listener)
    talker (roscpp_tutorials/talker)

auto-starting new master
process[master]: started with pid [17044]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 29f44e7e-40ff-11e7-848f-8cdcd4282014
process[rosout-1]: started with pid [17057]
started core service [/rosout]
process[listener-2]: started with pid [17060]
process[talker-3]: started with pid [17075]
[ INFO] [1495685033.174827502]: hello world 0
[ INFO] [1495685033.274863703]: hello world 1
[ INFO] [1495685033.374841763]: hello world 2
[ INFO] [1495685033.474848426]: hello world 3
[ INFO] [1495685033.574851120]: hello world 4
[ INFO] [1495685033.575218028]: I heard: [hello world 4]
[ INFO] [1495685033.674848264]: hello world 5
[ INFO] [1495685033.675070148]: I heard: [hello world 5]
[ INFO] [1495685033.774845563]: hello world 6
[ INFO] [1495685033.775095799]: I heard: [hello world 6]
[ INFO] [1495685033.874847475]: hello world 7
[ INFO] [1495685033.875101877]: I heard: [hello world 7]
[ INFO] [1495685033.974849567]: hello world 8
[ INFO] [1495685033.975095641]: I heard: [hello world 8]
[ INFO] [1495685034.074844666]: hello world 9
[ INFO] [1495685034.075093529]: I heard: [hello world 9]
[ INFO] [1495685034.174848640]: hello world 10
[ INFO] [1495685034.175096831]: I heard: [hello world 10]
[ INFO] [1495685034.274851912]: hello world 11
[ INFO] [1495685034.275102399]: I heard: [hello world 11]
[ INFO] [1495685034.374847570]: hello world 12
[ INFO] [1495685034.375106536]: I heard: [hello world 12]
[ INFO] [1495685034.474848302]: hello world 13
[ INFO] [1495685034.475098772]: I heard: [hello world 13]
[ INFO] [1495685034.574845042]: hello world 14
[ INFO] [1495685034.575095819]: I heard: [hello world 14]
[ INFO] [1495685034.674848374]: hello world 15
[ INFO] [1495685034.675091884]: I heard: [hello world 15]
^C[talker-3] killing on exit
[listener-2] killing on exit
[ INFO] [1495685034.774893976]: hello world 16
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
````

**Comment by dirk-thomas** [comment]
The parallel processing for parsing package manifests has been introduced in #171. So the problem is likely related to that.

When I run the launch command it seems to work fine (the talker and listener start as expected). But when I try to abort the running programm with `Ctrl-C` I get the *N* `KeyboardInterrupt` exceptions and have to kill the process with `Crtl-\`.

Can you please describe the exact steps you are performing. Your above descriptions seems to be slightly different and I want to make sure we cover all cases.

**Comment by k-okada** [comment]
Sorry, yes you're right , normally it runs as
```
When I run the launch command it seems to work fine (the talker and listener start as expected). But when I try to abort the running programm with Ctrl-C I get the N KeyboardInterrupt exceptions and have to kill the process with Crtl-\.
```

![catkin_ctk_175](https://cloud.githubusercontent.com/assets/493276/26437636/3502c250-4159-11e7-89d4-54b851207c32.gif)

```
 rm -fr build/ devel/ logs/ src/
 sudo apt-get install --reinstall python-catkin-pkg-modules python-catkin-pkg
 git clone https://github.com/ros/ros_tutorials src/ros_tutorials
 source /opt/ros/indigo/setup.bash 
 catkin b roscpp_tutorials
 source devel/setup.bash 
 roslaunch roscpp_tutorials talker_listener.launch
```

But if we create workspace with https://gist.github.com/k-okada/90a1cf5c85bbf4444a0a9b6beafaa265, (and compile, several errors are ok) then we can reproduce that behavior , I'm trying to narrow down the problem and provide minimum set , but not succeeded so far. I'll update if I have any progress.

**Comment by k-okada** [comment]
If we create 64 packages using
```
for j in $(seq 0 7); do
    for i in $(seq 0 7); do
        if (( i <= 1 )); then
            catkin_create_pkg test_$((j))_$((i))
        else
            catkin_create_pkg test_$((j))_$((i)) test_$((j))_$((i - 1))
        fi
    done
done
```
script in clean workspace, it tool 4-5 seconds to start talker/listener example, so my guess is that if we have complex dependency in workspace, it takes more time to actually starts nodes and this is what I see in the original report. Worst case is that it consumes all CPU power before it actually starts talker/listener nodes, which we have seen in our workspace.

**Comment by dirk-thomas** [comment]
Please see #176 which should address both problems: the KeyboardInterrupts from all workers as well as the performance regression in this use case.

**Comment by dirk-thomas** [comment]
Thank you for reporting this quickly!

**Comment by k-okada** [comment]
Thank you!, I have confirmed this solved our problem. Cc: @YutoUchimi
