### ISSUE TITLE
[catkin_generate_changelog] UnicodeDecodeError: 'utf8' codec can't decode byte 0x8f in position 1963: invalid start byte

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/catkin_pkg#181]
Similar to #179 I still see an encoding error.
With `Python3` I see different error.

I have a feeling that the root cause of the error is in one of the CHANGELOG.rst files, but from the error message it's hard to tell where that is.

```
$ dpkg -p python-catkin-pkg
Package: python-catkin-pkg
Priority: optional
Section: python
Installed-Size: 22
Maintainer: Dirk Thomas <dthomas@osrfoundation.org>
Architecture: all
Version: 0.3.5-1
Depends: python (>= 2.7), python (<< 2.8), python-docutils, python-dateutil, python-argparse, python-catkin-pkg-modules
Conflicts: catkin, python3-catkin-pkg
Size: 2398
Description: catkin package library
 Library for retrieving information about catkin packages.
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
$ mkdir /tmp/moveit_kinetic/
$ cd /tmp/moveit_kinetic/
$ git clone git@github.com:ros-planning/moveit.git
Cloning into 'moveit'...
:
$ cd moveit/
$ git checkout indigo-devel
Branch indigo-devel set up to track remote branch indigo-devel from origin.
Switched to a new branch 'indigo-devel'
$ git log -1 --stat
commit aecd96811495c5b5037b7a587d98c29eb7425b13
Author: Isaac I.Y. Saito <130s@users.noreply.github.com>
Date:   Wed Jun 7 05:10:45 2017 -0700

    checks for empty name arrays messages before parsing the robot state message data (#499) (#518)

 moveit_core/robot_state/src/conversions.cpp | 14 ++++++++++++--
 1 file changed, 12 insertions(+), 2 deletions(-)
$ catkin_generate_changelog
Found packages: chomp_motion_planner, moveit, moveit_commander, moveit_controller_manager_example, moveit_core, moveit_experimental, moveit_fake_controller_manager, moveit_full, moveit_full_pr2, moveit_kinematics, moveit_planners, moveit_planners_chomp, moveit_planners_ompl, moveit_plugins, moveit_ros, moveit_ros_benchmarks, moveit_ros_benchmarks_gui, moveit_ros_control_interface, moveit_ros_manipulation, moveit_ros_move_group, moveit_ros_perception, moveit_ros_planning, moveit_ros_planning_interface, moveit_ros_robot_interaction, moveit_ros_visualization, moveit_ros_warehouse, moveit_runtime, moveit_setup_assistant, moveit_simple_controller_manager
Querying commit information since latest tag...
Updating forthcoming section of changelog files...
- updating 'moveit_plugins/moveit_ros_control_interface/CHANGELOG.rst'
- updating 'moveit_plugins/moveit_controller_manager_example/CHANGELOG.rst'
- updating 'moveit_plugins/moveit_fake_controller_manager/CHANGELOG.rst'
- updating 'moveit_runtime/CHANGELOG.rst'
- updating 'moveit_ros/perception/CHANGELOG.rst'
- updating 'moveit_experimental/CHANGELOG.rst'
- updating 'moveit_ros/move_group/CHANGELOG.rst'
- updating 'moveit_setup_assistant/CHANGELOG.rst'
- updating 'moveit_ros/robot_interaction/CHANGELOG.rst'
- updating 'moveit_plugins/moveit_plugins/CHANGELOG.rst'
- updating 'moveit_ros/benchmarks/CHANGELOG.rst'
- updating 'moveit_ros/warehouse/CHANGELOG.rst'
- updating 'moveit_kinematics/CHANGELOG.rst'
- updating 'moveit_commander/CHANGELOG.rst'
- updating 'moveit_ros/visualization/CHANGELOG.rst'
Traceback (most recent call last):
  File "/usr/bin/catkin_generate_changelog", line 9, in <module>
    load_entry_point('catkin-pkg==0.3.5', 'console_scripts', 'catkin_generate_changelog')()
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/cli/generate_changelog.py", line 125, in main_catching_runtime_error
    main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/cli/generate_changelog.py", line 118, in main
    update_changelogs(base_path, packages_with, tag2log_entries, logger=logging, vcs_client=vcs_client, skip_contributors=args.skip_contributors)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/changelog_generator.py", line 123, in update_changelogs
    data = f.read().decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8f in position 1963: invalid start byte
$ ll moveit_ros/visualization/CHANGELOG.rst
-rw-rw-r-- 1 rosnoodle rosnoodle 12K Jun  7 10:35 moveit_ros/visualization/CHANGELOG.rst
$ date
Wed Jun  7 10:36:01 PDT 2017
```

```
$ sudo apt-get install python3-ros-buildfarm
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python-configparser python-ros-buildfarm-modules
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  python3-catkin-pkg-modules python3-ros-buildfarm-modules
  python3-rosdistro-modules python3-rospkg-modules python3-setuptools
  python3-yaml
The following packages will be REMOVED:
  python-ros-buildfarm
The following NEW packages will be installed:
  python3-catkin-pkg-modules python3-ros-buildfarm
  python3-ros-buildfarm-modules python3-rosdistro-modules
  python3-rospkg-modules python3-setuptools python3-yaml
0 upgraded, 7 newly installed, 1 to remove and 0 not upgraded.
:
$ python3 `which catkin_generate_changelog`
Traceback (most recent call last):
  File "/usr/bin/catkin_generate_changelog", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: catkin-pkg==0.3.5
```

**Comment by dirk-thomas** [comment]
If I look at the [current changelog file](https://github.com/ros-planning/moveit/blob/aecd96811495c5b5037b7a587d98c29eb7425b13/moveit_ros/visualization/CHANGELOG.rst) line 44 looks corrupted to me: "Michael G���rner"

After fixing the existing file please try again. I expect it to work then.

**Comment by 130s** [comment]
Thank you for taking a look! It works after fixing the garbled text.

Interestingly this issue hasn't happened before AFAIK with the same reported package...the problematic log entry is 2016-06-20, and there has been multiple newer logs since then that were generated by the same `catkin_generate_changelog` command. I don't think I would overlook if the same issue had happened. 
Could the tool ignore it before? I mean it's good that the newest version detects the format issue like this time. I'm just wondering.

**Comment by dirk-thomas** [comment]
> Could the tool ignore it before?

Yes, before the tool didn't consider the encoding and left it up to Python to read the file.

> It works after fixing the garbled text.

Thanks for checking. I will close this ticket then.
