### ISSUE TITLE
Error when running catkin_prepare_release with non catkin build type

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-infrastructure/catkin_pkg#338]
``` bash
Traceback (most recent call last):
  File "/usr/bin/catkin_prepare_release", line 33, in <module>
    sys.exit(load_entry_point('catkin-pkg==0.5.0', 'console_scripts', 'catkin_prepare_release')())
  File "/usr/lib/python3/dist-packages/catkin_pkg/cli/prepare_release.py", line 217, in main
    _main()
  File "/usr/lib/python3/dist-packages/catkin_pkg/cli/prepare_release.py", line 280, in _main
    "@{yf}Warning: the following package are not of build_type %s and may require manual steps to release': %s" %
TypeError: not enough arguments for format string
```

**Comment by cottsay** [comment]
This looks like another regression from #331. Thanks for reporting.

**Comment by Levi-Armstrong** [comment]
I was able to comment out the print statement at line 280 to get things working for now.
